# Site settings
title: Desarrollo web para latinos
header-img: img/home-bg.png
email: u70391278@continental.edu.pe
copyright_name: frenre29
description: > # this means to ignore newlines until "baseurl:"
  La informática es una apuesta a todo o nada... pero lo lograremos!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  frenre29
learn_profile: frenre29
email_username: u70391278@continental.edu.pe

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
